### ISSUE TITLE
Protótipo empresas

### ISSUE THREAD

**Issue by MoacirMSJ** [DS-roxo-lavanda-22-2/docs#15]
Com base nos dados presente no branstorming  prototipar telas:

- Lista de empresas
- Detalhes de uma empresa.
- Cadastro de uma empresa.

Link protótipo: https://www.figma.com/file/ktHGX9MXbEDNIWhR4a4Zf5/DS-team-library?node-id=425%3A247&t=ChNkiLseKYsv4YI4-0

**Obs**: Seguir como o estilo e cores da tela inicial.

**Comment by Edyane** [comment]
Detalhes da empresa = botão saiba mais que vai redirecionar para o site da empresa.
