### ISSUE TITLE
Prototipar Logn

### ISSUE THREAD

**Issue by MoacirMSJ** [DS-roxo-lavanda-22-2/docs#19]
Com base nos dados presente no branstorming  prototipar telas:

- Login do admin(username e senha)

Link protótipo: https://www.figma.com/file/ktHGX9MXbEDNIWhR4a4Zf5/DS-team-library?node-id=425%3A247&t=ChNkiLseKYsv4YI4-0

**Obs**: Seguir como o estilo e cores da tela inicial.

**Comment by benlacerda** [comment]
Fiz um protótipo da tela.
